#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jan 27 17:54:26 EST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 0f3a24578ef64740b5aa533366da299b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot user_logic_behav xil_defaultlib.user_logic -log elaborate.log"
xelab -wto 0f3a24578ef64740b5aa533366da299b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot user_logic_behav xil_defaultlib.user_logic -log elaborate.log

