# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_floating_point_0_0/system_floating_point_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_floating_point_0_0 || ORIG_REF_NAME==system_floating_point_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_0/system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/system/ip/system_smartconnect_0_0/system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_smartconnect_0_0 || ORIG_REF_NAME==system_smartconnect_0_0} -quiet] -quiet

# Block Designs: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/bd_919a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_0/bd_919a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/bd_919a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/bd_919a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/bd_919a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/bd_919a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/bd_919a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_7/bd_919a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_8/bd_919a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_9/bd_919a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_10/bd_919a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_11/bd_919a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/bd_919a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_13/bd_919a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_14/bd_919a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_15/bd_919a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_16/bd_919a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_17/bd_919a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_18/bd_919a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/bd_919a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/bd_919a_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/bd_919a_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_22/bd_919a_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_23/bd_919a_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_24/bd_919a_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/bd_919a_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_26/bd_919a_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_27/bd_919a_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_28/bd_919a_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_29/bd_919a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_30/bd_919a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_31/bd_919a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_32/bd_919a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_33/bd_919a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_34/bd_919a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_35/bd_919a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_0/system_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_0/system_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/bd_919a_arsw_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/bd_919a_rsw_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/bd_919a_awsw_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/bd_919a_wsw_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/bd_919a_bsw_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_10/bd_919a_s00a2s_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_11/bd_919a_sarn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/bd_919a_srn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_13/bd_919a_sawn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_14/bd_919a_swn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_15/bd_919a_sbn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/bd_919a_s01a2s_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/bd_919a_sarn_1_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/bd_919a_srn_1_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/bd_919a_s02a2s_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_26/bd_919a_sawn_1_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_27/bd_919a_swn_1_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_28/bd_919a_sbn_1_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_29/bd_919a_m00s2a_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_30/bd_919a_m00arn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_31/bd_919a_m00rn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_32/bd_919a_m00awn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_33/bd_919a_m00wn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_34/bd_919a_m00bn_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_smartconnect_0_0/ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: /home/nick/ECEC402/homework_4/fp_acc/fp_acc.gen/sources_1/bd/system/system_ooc.xdc
